### ISSUE TITLE
Not working on Heroku

### ISSUE THREAD

**Issue by oxtx** [sniper365/packages#1]
Hi @sniper365 
Awesome.. Thanks for sharing an awesome repo
... but I can't see the demo on heroku

**Comment by sniper365** [comment]
Hey @Jackie1019 
Deployed to vercel and Updated ReadMe.md

Enjoy..

**Comment by oxtx** [comment]
Good job 👍 

> Hey @Jackie1019 Deployed to vercel and Updated ReadMe.md
> 
> Enjoy..
